CREATE TABLE IF NOT EXISTS project (
  id int AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  desc VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS milestone (
  id int AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  desc VARCHAR(255),
  pid int
);